global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:5090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:5100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:5080']

  - job_name: 'kube_state_metrics'
    static_configs:
      - targets: ['kube_state_metrics:5081']

  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:5443  # Custom Kubernetes API port
      - source_labels: [__meta_kubernetes_node_name]
        target_label: instance

rule_files:
  - "alert_rules.yml"
