global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # Service name for Prometheus

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  # Service name for Node Exporter

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']  # Service name for cAdvisor

  - job_name: 'kube_state_metrics'
    static_configs:
      - targets: ['kube_state_metrics:8081']  # Service name for Kube-State-Metrics

rule_files:
  - "alert_rules.yml"
